/*
 *
 * Home constants
 *
 */

export const POPULAR_TYPE_PHARMA = 'Home/POPULAR_TYPE_PHARMA'
export const POPULAR_TYPE_GAS = 'Home/POPULAR_TYPE_GAS'
export const POPULAR_TYPE_SCHOOL = 'Home/POPULAR_TYPE_SCHOOL'
export const POPULAR_TYPE_REUSTARANTS = 'Home/POPULAR_TYPE_REUSTARANTS'
export const POPULAR_TYPE_NONE = 'Home/POPULAR_TYPE_REUSTARANTS'

export const MAP_DATA_TYPE_MARKERS = 'Home/MAP_DATA_TYPE_MARKERS'
export const MAP_DATA_TYPE_POPULAR = 'Home/MAP_DATA_TYPE_POPULAR'

export const FETCH_USER_REQUEST_ACTION = 'Profile/FETCH_USER_REQUEST_ACTION'
export const FETCH_USER_SUCCESS_ACTION = 'Profile/FETCH_USER_SUCCESS_ACTION'
export const FETCH_USER_FAILURE_ACTION = 'Profile/FETCH_USER_FAILURE_ACTION'

export const CHANGE_MAP_DATA_TYPE = 'Profile/CHANGE_MAP_DATA_TYPE'
export const CHANGE_POPULAR_TYPE = 'Profile/CHANGE_POPULAR_TYPE'

export const CLEAR_MARKERS = 'Profile/CLEAR_MARKERS'

export const ADD_MARKER = 'Profile/ADD_MARKER'

export const DELETE_MARKERS = 'Profile/DELETE_MARKERS'

export const CHANGE_CENTER = 'Profile/CHANGE_CENTER'

export const CHANGE_ZOOM = 'Profile/CHANGE_ZOOM'

export const FETCH_MARKERS_REQUEST_ACTION = 'Profile/FETCH_MARKERS_REQUEST_ACTION'
export const FETCH_MARKERS_SUCCESS_ACTION = 'Profile/FETCH_MARKERS_SUCCESS_ACTION'
export const FETCH_MARKERS_FAILURE_ACTION = 'Profile/FETCH_MARKERS_FAILURE_ACTION'

export const SAVE_MARKERS_REQUEST_ACTION = 'Profile/SAVE_MARKERS_REQUEST_ACTION'
export const SAVE_MARKERS_SUCCESS_ACTION = 'Profile/SAVE_MARKERS_SUCCESS_ACTION'
export const SAVE_MARKERS_FAILURE_ACTION = 'Profile/SAVE_MARKERS_FAILURE_ACTION'
